app/routes/pc_routes.py
from flask import Blueprint, request, render_template,redirect,url_for
from app import db
from app.models.Pc import Pc

bp = Blueprint('Pc', __name__)

@bp.route('/Pc', methods=['GET', 'POST'])
def index():
    return render_template("Pc.html")

@bp.route('/nosotros', methods=['GET'])
def XD():
    return render_template("nosotros.html")

@bp.route('/Pc2', methods=['GET'])
def XD2():
    data = Pc.query.all()
    return render_template("lista.html", data=data)

@bp.route('/Pc/add', methods=['POST'])
def add():
    try:
        marca = request.form.get('marca')
        codigo = request.form.get('codigo')
        color = request.form.get('color')
        desp = request.form.get('desp')
        estado = request.form.get('estado')
        estado = estado == '1'

        new_Pc = Pc(marca=marca, codigo=codigo, color=color, desp=desp, estado=estado)
        db.session.add(new_Pc)
        db.session.commit()
        return redirect(url_for('Pc.index')) 
        
    except Exception as e:
        db.session.rollback()
        return f"Error al agregar Pc: {str(e)}", 500

@bp.route('/Pc/edit/<int:id>', methods=['POST'])
def edit(id):
    try:
        pc = Pc.query.get_or_404(id)
        if pc:
            pc.estado = False
            db.session.commit()
            return redirect(url_for('Pc.XD2'))
        else:
            return "Pc no encontrado", 404
    except Exception as e:
        db.session.rollback()
        return f"Error al editar Pc: {str(e)}", 500

@bp.route('/Pc/editt/<int:id>', methods=['POST'])
def editt(id):
    try:
        pc = Pc.query.get_or_404(id)
        if pc:
            pc.estado = True
            db.session.commit()
            return redirect(url_for('Pc.XD2'))
        else:
            return "Pc no encontrado", 404
    except Exception as e:
        db.session.rollback()
        return f"Error al editar Pc: {str(e)}", 500
@bp.route('/Pc/delete/<int:id>', methods=['POST'])
def delete(id):
    try:
        pc= Pc.query.get_or_404(id)

        if pc:
            db.session.delete(pc)
            db.session.commit()
            return redirect(url_for('Pc.XD2'))
        else:
            return "Pc no encontrado", 404
    except Exception as e:
        db.session.rollback()
        return f"Error al eliminar Pc: {str(e)}", 500
    

app/routes/session_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models.Celador import Celador

auth_bp = Blueprint('session', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        nombre = request.form['nombre']
        contraseña = request.form['contraseña']
        
        user = Celador.query.filter_by(nombre=nombre, contraseña=contraseña).first()

        if user:
            print("is activa",current_user.is_authenticated)
            login_user(user)
            flash("Login successful!", "success")
            return redirect(url_for('Pc.index'))  # Corregir esta redirección
        
        flash('Invalid credentials. Please try again.', 'danger')
    
    if current_user.is_authenticated:
        return redirect(url_for('Pc.index')) 
    
    return redirect(url_for('Celador.index'))

@auth_bp.route('/dashboard')
@login_required
def dashboard():
    return f'Welcome, {current_user.nombreCelador}! This is your dashboard.'

@auth_bp.route('/logout', methods=['POST'])  # Añadir corchetes alrededor de 'POST'
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('Celador.index'))

@auth_bp.route('/inicio')  # Añadir corchetes alrededor de 'POST'
def inicio():
    return render_template("index.html")

app/templates/partials/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ALMACEN SENA</title>
    <!-- Enlaces a Bootstrap CSS y FontAwesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <!-- Estilos personalizados -->
    <style>
        .navbar {
            background-color: #343a40; /* Color de fondo del navbar */
        }
        .navbar-brand {
            font-size: 1.5rem;
            font-weight: bold;
        }
        .navbar-nav .nav-link {
            color: #ffffff; /* Color de texto de los enlaces */
            font-size: 1.1rem;
            margin-right: 10px;
        }
        .navbar-nav .nav-link:hover {
            color: #ffffff; /* Color de texto al pasar el mouse por encima */
        }
        .navbar-toggler {
            border-color: #ffffff; /* Color del ícono del botón de alternancia */
        }
        .navbar-toggler-icon {
            color: #ffffff; /* Color del icono del botón de alternancia */
        }
        .btn-logout {
            background-image: url('{{ url_for("static", filename="/imagenes/gif3.gif") }}'); /* Reemplaza 'ruta/a/tu/imagen.gif' con la URL de tu GIF */
            background-size: cover;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: opacity 0.3s;
        }

        .btn-logout:hover {
            opacity: 0.8;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">ALMACEN SENA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown"
                aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('Pc.index') }}">
                            <i class="fas fa-laptop"></i> REGISTRO DE EQUIPOS
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('Pc.XD2') }}">
                            <i class="fas fa-laptop"></i> LISTA DE EQUIPOS
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-info-circle"></i> ACERCA DE NOSOTROS
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li><a class="dropdown-item" href="{{ url_for('Pc.XD') }}">Detalles de Servicio</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('Pc.XD') }}">Condiciones de Uso</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('Pc.XD') }}">Lo que Hacemos</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-envelope"></i> CONTACTENOS
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li><a class="dropdown-item" href="https://twitter.com/?lang=es"><i class="fab fa-twitter"></i> Twitter</a></li>
                            <li><a class="dropdown-item" href="https://www.instagram.com"><i class="fab fa-instagram"></i> Instagram</a></li>
                            <li><a class="dropdown-item" href="https://www.facebook.com"><i class="fab fa-facebook"></i> Facebook</a></li>
                            <li><a class="dropdown-item" href="https://www.youtube.com"><i class="fab fa-youtube"></i> Youtube</a></li>
                            <li><a class="dropdown-item" href="https://www.tiktok.com/en/"><i class="fab fa-tiktok"></i> TikTok</a></li>
                            <li><a class="dropdown-item" href="https://oferta.senasofiaplus.edu.co/sofia-oferta/inicio-sofia-plus.html">Otros</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <form action="{{ url_for('session.logout') }}" method="post">
                            <button type="submit" class="btn btn-logout">CERRAR SESION</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>
</html>