app/models/Pc.py
from app import db


class Pc(db.Model):
    __tablename__ = 'Pc'
    idPc = db.Column(db.Integer, primary_key=True)
    marca = db.Column(db.String(45))
    codigo = db.Column(db.String(45))
    color = db.Column(db.String(45))
    desp = db.Column(db.String(45))
    estado = db.Column(db.Boolean)

app/routes/celador_routes.py
from flask import Blueprint, request, render_template
from app import db
from app.models.Celador import Celador 

bp = Blueprint('Celador', __name__)

@bp.route('/')
def index():
    return render_template("inicio.html")

@bp.route('/add', methods=['POST'])
def add():
    try:
        cedula=request.form.get('cedula')
        nombre=request.form.get('nombre')
        Aprellido=request.form.get('Aprellido')
        telefono=request.form.get('telefono')
        contraseña=request.form.get('contraseña')
        
        new_admin = Celador(cedula=cedula,nombre=nombre,Aprellido=Aprellido,telefono=telefono,contraseña=contraseña)
        db.session.add(new_admin)
        db.session.commit()
        return render_template("index.html")
    except Exception as e:
        db.session.rollback()
        return f"Error al agregar Celador: {str(e)}", 500

@bp.route('/edit/<int:id>', methods=['PUT'])
def edit(id):
    try:
        admin = db.session.query(Celador).get(id)
        if admin:
            cedula=request.form.get('cedula')
            nombre=request.form.get('nombre')
            Aprellido=request.form.get('Aprellido')
            telefono=request.form.get('telefono')
            contraseña=request.form.get('contraseña')
        
            id = Celador(cedula=cedula,nombre=nombre,Aprellido=Aprellido,telefono=telefono,contraseña=contraseña)
            db.session.commit()
            return render_template("welcome.html")
        else:
            return "Celador no encontrado", 404
    except Exception as e:
        db.session.rollback()
        return f"Error al editar Celador: {str(e)}", 500

@bp.route('/delete/<int:id>', methods=['DELETE'])
def delete(id):
    try:
        admin = db.session.query(Celador).get(id)
        if admin:
            db.session.delete(admin)
            db.session.commit()
            return "Celador eliminado correctamente", 200
        else:
            return "Celador no encontrado", 404
    except Exception as e:
        db.session.rollback()
        return f"Error al eliminar Celador: {str(e)}", 500

app/routes/pc_routes.py
from flask import Blueprint, request, render_template,redirect,url_for
from app import db
from app.models.Pc import Pc

bp = Blueprint('Pc', __name__)

@bp.route('/Pc', methods=['GET', 'POST'])
def index():
    return render_template("Pc.html")

@bp.route('/nosotros', methods=['GET'])
def XD():
    return render_template("nosotros.html")

@bp.route('/Pc2', methods=['GET'])
def XD2():
    data = Pc.query.all()
    return render_template("lista.html", data=data)

@bp.route('/Pc/add', methods=['POST'])
def add():
    try:
        marca = request.form.get('marca')
        codigo = request.form.get('codigo')
        color = request.form.get('color')
        desp = request.form.get('desp')
        estado = request.form.get('estado')
        estado = estado == '1'

        new_Pc = Pc(marca=marca, codigo=codigo, color=color, desp=desp, estado=estado)
        db.session.add(new_Pc)
        db.session.commit()
        return redirect(url_for('Pc.index')) 
        
    except Exception as e:
        db.session.rollback()
        return f"Error al agregar Pc: {str(e)}", 500

@bp.route('/Pc/edit/<int:id>', methods=['POST'])
def edit(id):
    try:
        pc = Pc.query.get_or_404(id)
        if pc:
            pc.estado = False
            db.session.commit()
            return redirect(url_for('Pc.XD2'))
        else:
            return "Pc no encontrado", 404
    except Exception as e:
        db.session.rollback()
        return f"Error al editar Pc: {str(e)}", 500

@bp.route('/Pc/editt/<int:id>', methods=['POST'])
def editt(id):
    try:
        pc = Pc.query.get_or_404(id)
        if pc:
            pc.estado = True
            db.session.commit()
            return redirect(url_for('Pc.XD2'))
        else:
            return "Pc no encontrado", 404
    except Exception as e:
        db.session.rollback()
        return f"Error al editar Pc: {str(e)}", 500
@bp.route('/Pc/delete/<int:id>', methods=['POST'])
def delete(id):
    try:
        pc= Pc.query.get_or_404(id)

        if pc:
            db.session.delete(pc)
            db.session.commit()
            return redirect(url_for('Pc.XD2'))
        else:
            return "Pc no encontrado", 404
    except Exception as e:
        db.session.rollback()
        return f"Error al eliminar Pc: {str(e)}", 500
    

app/routes/session_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models.Celador import Celador

auth_bp = Blueprint('session', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        nombre = request.form['nombre']
        contraseña = request.form['contraseña']
        
        user = Celador.query.filter_by(nombre=nombre, contraseña=contraseña).first()

        if user:
            print("is activa",current_user.is_authenticated)
            login_user(user)
            flash("Login successful!", "success")
            return redirect(url_for('Pc.index'))  # Corregir esta redirección
        
        flash('Invalid credentials. Please try again.', 'danger')
    
    if current_user.is_authenticated:
        return redirect(url_for('Pc.index')) 
    
    return redirect(url_for('Celador.index'))

@auth_bp.route('/dashboard')
@login_required
def dashboard():
    return f'Welcome, {current_user.nombreCelador}! This is your dashboard.'

@auth_bp.route('/logout', methods=['POST'])  # Añadir corchetes alrededor de 'POST'
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('Celador.index'))

@auth_bp.route('/inicio')  # Añadir corchetes alrededor de 'POST'
def inicio():
    return render_template("index.html")

app/templates/Pc.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de Computadoras</title>
    <!-- Enlaces a Bootstrap CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Estilos personalizados -->
    <style>
        body {
            background-color: black; /* Color de fondo */
            font-family: Arial, sans-serif;
            color: white;
            background-image: url('{{ url_for("static", filename="/imagenes/gif.gif") }}');
            background-size: cover;
            background-position: center;
        }
        .container {
            max-width: 400px;
            margin: 0 auto;
            margin-top: 39px;
            text-align: center;
            border: 2px solid red;
            padding: 20px;
            border-radius: 10px;
            background-color: black;
            color: white;
            width: 50%;
        }
        h1 {
            font-size: 28px;
            text-align: center;
            margin-bottom: 30px;
            color: #333;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        input[type="text"],
        input[type="password"] {
            padding: 10px;
            width: 100%;
            margin-bottom: 10px;
            border: none;
            border-radius: 5px;
        }
        input[type="text"]:focus,
        input[type="password"]:focus {
            padding: 10px 20px;
            background-color: red;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        
        .botones input[type="radio"] {
            display: none; /* Oculta el botón de radio */
        }

        .botones label {
            display: inline-block;
            padding: 5px 10px;
            background-color: #007bff;
            color: white;
            border-radius: 5px;
            cursor: pointer;
            width:211px;
        }

        .botones input[type="radio"]:checked + label {
            background-color: red;
        }

        button[type="submit"] {
            width: 75%;
            padding: 10px;
            background-color: #007bff;
            border: none;
            color: #fff;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }

        .miclase{
            width: 40% !important;
        }
        
    </style>
</head>
<body>
    {% include 'partials/nav.html' %}
    <div class="container miclase">
        <h1>Registro de Computadoras</h1>
        <form action="{{ url_for('Pc.add') }}" method="post">
            <div class="form-group">
                <input type="hidden" class="form-control" id="idPc" name="Pc">
                <label for="marca">Marca:</label>
                <input type="text" class="form-control" id="marca" placeholder="Ingrese la marca" name="marca" required>
            </div>
            <div class="form-group">
                <label for="codigo">Código:</label>
                <input type="text" class="form-control" id="codigo" placeholder="Ingrese el código" name="codigo" required>
            </div>
            <div class="form-group">
                <label for="color">Color:</label>
                <input type="text" class="form-control" id="color" placeholder="Ingrese el color" name="color" required>
            </div>
            <div class="form-group">
                <label for="desp">Descripción:</label>
                <input type="text" class="form-control" id="desp" placeholder="Ingrese una descripción del equipo" name="desp" required>
            </div>
            <div class="form-group">
                <label>Estado:</label><br>
                <div class="botones">
                    <input class="form-check-input" type="radio" name="estado" id="prestado" value="1" required>
                    <label class="form-check-label" for="prestado">Prestado</label>
                </div>
                <div class="botones">
                    <input class="form-check-input" type="radio" name="estado" id="no-prestado" value="0" required>
                    <label class="form-check-label" for="no-prestado">No prestado</label>
                </div>
            </div>
            <button type="submit">Enviar</button>
        </form>
    </div>
</body>
</html>
    

app/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            color: red;
            font-family: Arial, sans-serif;
            text-align: center;
            background-image: url('{{ url_for("static", filename="/imagenes/gif2.gif") }}');
            background-size: cover;
            background-position: center;
        }
        .login-container {
            margin-top: 100px;
            border: 2px solid red; /* Añade un borde rojo alrededor del contenedor */
            padding: 20px; /* Agrega un espacio interno para que el contenido no se pegue al borde */
            display: inline-block; /* Para que el contenedor no se extienda al 100% del ancho */
            background-color: black; /* Fondo del contenedor negro */
        }
        .login-container input[type="text"],
        .login-container input[type="password"] {
            padding: 10px;
            width: 200px;
            margin-bottom: 10px;
            border: none;
            border-radius: 5px;
        }
        .login-container button[type="submit"],
        .login-container input[type="button"],
        .Registrarse {
            padding: 10px 20px;
            background-color: red;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        #message {
            color: red;
            font-size: 14px;
            margin-top: 10px;
        }

        .Registrarse {
            font-size: 13px;
            text-decoration: none;
        }

    </style>
</head>
<body>
    <div class="login-container">
        <h2>Iniciar sesión</h2>
        <form id="loginForm" action="{{ url_for('session.login') }}" method="post" onsubmit="return showWelcomeAlert()">
            <input type="text" name="nombre" id="nombre" placeholder="Nombre" required><br>
            <input type="password" name="contraseña" id="contraseña" placeholder="Contraseña" required><br>
            <button type="submit" value="">Iniciar sesión</button>
            <a class="Registrarse" href="/Registar" target="_blank" rel="noopener noreferrer">Registrarse</a>

        </form>
        <div id="message"></div>
    </div>

    <script>
        function showWelcomeAlert() {
            var nombre = document.getElementById("nombre").value;
            alert("¡Bienvenido, " + nombre + "!");
            return true; // Para enviar el formulario después de mostrar la alerta
        }
    </script>
</body>
</html>

app/templates/inicio.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SENA - Servicio Nacional de Aprendizaje</title>
    <link rel="stylesheet" href="">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: green;
            color: #fff;
            padding: 20px;
            text-align: center;
        }
        nav {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
        }
        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }
        nav ul li {
            display: inline;
            margin-right: 20px;
        }
        nav ul li a {
            color: #fff;
            text-decoration: none;
            font-weight: bold;
        }
        section {
            padding: 20px;
            margin: 20px;
        }
        footer {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 10px;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
    <!-- Enlace a Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Estilos personalizados para el carrusel -->
    <style>
        /* Ajuste de tamaño para las imágenes */
        .carousel-inner img {
            width: 40%;
            height: 40%;
        }
    </style>
</head>
<body>
    <header>
        <h1>SENA - Servicio Nacional de Aprendizaje</h1>
        <h1>Prestamo de computadoras</h1>
    </header>
    <nav>
        <ul>
            <li><a href="/inicio">Iniciar Sesion</a></li>
            <li><a href="/Registar">Registrarse</a></li>
        </ul>
    </nav>
   <center><h2>Préstamo de Computadoras</h2></center> 
    <p>En el SENA, ofrecemos servicios de préstamo de computadoras para apoyar tu proceso de aprendizaje. Nuestros estudiantes tienen la oportunidad de acceder a computadoras de última generación para realizar sus actividades académicas y proyectos.</p>
    <p>Para solicitar el préstamo de una computadora, debes dirigirte a la biblioteca de tu sede más cercana y presentar tu identificación estudiantil. El préstamo de equipos está sujeto a disponibilidad y reglamentos internos del SENA.</p>
</section>


    </section>

    <!-- Carrusel -->
    <div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicadores -->
            <ul class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ul>
            <!-- Imágenes del carrusel -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{{ url_for('static', filename='/imagenes/images.png') }}" alt="Imagen 1">
                </div>
                <div class="carousel-item">
                    <img src="{{ url_for('static', filename='/imagenes/imagen 2.avif') }}" alt="Imagen 2">
                </div>
                <div class="carousel-item">
                    <img src="{{ url_for('static', filename='/imagenes/imagen3.jpg') }}" alt="Imagen 3">
                </div>
            </div>
            <!-- Controles del carrusel -->
            <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <footer>
        <p>Derechos reservados © SENA 2024</p>
    </footer>

    <!-- Enlace a jQuery, Popper.js y Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/lista.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Equipos</title>
    <style>
        body {
            background-color: black;
            color: red;
            font-family: Arial, sans-serif;
            background-image: url('{{ url_for("static", filename="/imagenes/gif3.gif") }}');
            background-size: cover;
            background-position: center;
        }

        .delete-button {
            background-color: #ff3333;
            color: white;
            border: none;
            padding: 5px 10px;
            border-radius: 5px;
            cursor: pointer;
        }

        .table {
            border-collapse: collapse;
            width: 100%;
            background-color: #333; /* Cambiar el color de fondo de la tabla */
            color: white; /* Cambiar el color del texto de la tabla */
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #ff3333;
            color: white;
        }

        tr:nth-child(even) {
            background-color: #555; /* Cambiar el color de fondo de las filas pares */
        }

        tr:nth-child(odd) {
            background-color: #444; /* Cambiar el color de fondo de las filas impares */
        }
    </style>
</head>
<body>
    {% include 'partials/nav.html' %}
    <center><h3 style="color: white;" >Lista de Equipos</h3></center>
    <table class="table">
        <thead>
            <tr>
                <th>ID Pc</th>
                <th>marca</th>
                <th>codigo</th>
                <th>color</th>
                <th>descripcion</th>
                <th>estado</th>
                <th>Acción</th> <!-- Columna para el botón de eliminar -->
            </tr>
        </thead>
        <tbody>
            {% for Pc in data %}
                <form action="{{ url_for('Pc.delete', id=Pc.idPc) }}" method="post">
                    <tr>
                        <td>{{ Pc.idPc }}</td>
                        <td>{{ Pc.marca }}</td>
                        <td>{{ Pc.codigo }}</td>
                        <td>{{ Pc.color }}</td>
                        <td>{{ Pc.desp }}</td>
                        <td>
                            {% if Pc.estado %}
                                Prestado
                            {% else %}
                                No prestado
                            {% endif %}
                        </td>
                        <td>
                            <button class="delete-button">Eliminar</button>
                            <button formaction="{{ url_for('Pc.edit', id=Pc.idPc) }}" class="delete-button">Devolución</button>
                            <button formaction="{{ url_for('Pc.editt', id=Pc.idPc) }}" class="delete-button">Prestamo</button>
                        </td>
                    </tr>
                </form>
            {% endfor %}
        </tbody>
    </table>

    <!-- Script para manejar la eliminación del equipo -->
    <script>
        function eliminarEquipo(idPc) {
            // Aquí debes implementar la lógica para eliminar el equipo con el ID proporcionado
            // Puedes usar JavaScript para enviar una solicitud al servidor para eliminar el equipo de la base de datos
            // Por ejemplo, puedes utilizar AJAX para enviar una solicitud DELETE al servidor
            // Una vez que el equipo se elimine correctamente, puedes recargar la página o actualizar la lista de equipos sin recargar la página
            console.log('Eliminar equipo con ID: ' + idPc);
        }
    </script>
</body>
</html>

app/templates/nosotros.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="static/bootstrap-5.3.0-alpha1-dist/resources/css/app.css">
    <script type="module" src="static/bootstrap-5.3.0-alpha1-dist/resources/js/app.js" defer></script>
    <link rel="stylesheet" href="static/bootstrap-5.3.0-alpha1-dist/resources/css/Bienvenido.css">
    <script type="module" src="static/bootstrap-5.3.0-alpha1-dist/resources/js/Bienvenido.js" defer></script>
    <title>nosotros</title>
</head>
<body>
    {% include 'partials/nav.html' %}
    <div class="container">
        <h1 class="mt-5">Acerca de Nosotros</h1>
        <hr>

        <!-- Detalles de Servicio -->
        <section id="detalles-servicio" class="mt-4">
            <h2>Detalles de Servicio</h2>
            <p>
                Ingreso:

Registro de detalles del equipo.
Inspección y configuración inicial.
Asignación a un usuario o departamento específico.
Período de Uso:

Monitoreo continuo del estado y rendimiento del equipo.
Salida:

Registro detallado de la devolución.
Verificación del estado y eliminación segura de datos si es necesario.
Este servicio garantiza una administración completa y eficiente de los equipos desde su ingreso hasta su salida, contribuyendo a la eficiencia operativa y la seguridad de los activos tecnológicos.
            </p>
        </section>

        <hr>

        <!-- Condiciones de Uso -->
        <section id="condiciones-uso" class="mt-4">
            <h2>Condiciones de Uso</h2>
            <p>
                Uso Adecuado:

Los equipos deben utilizarse únicamente para fines laborales y autorizados.
Cuidado del Equipo:

Los usuarios son responsables de mantener el equipo en buen estado y reportar cualquier daño.
Seguridad de Datos:

Prohibición de instalación de software no autorizado.
Cumplimiento de políticas de seguridad de datos al salir.
Reporte de Incidentes:

Los usuarios deben informar cualquier incidente, pérdida o robo de equipo de inmediato.
            </p>
        </section>

        <hr>

        <!-- Lo Que Hacemos -->
        <section id="lo-que-hacemos" class="mt-4">
            <h2>Lo Que Hacemos</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Nullam auctor, velit eget ullamcorper rhoncus, tortor velit
                laoreet felis, nec lacinia libero ex eu velit. In tincidunt
                libero ac risus ullamcorper, a ultricies sapien ultrices.
                Nulla facilisi. Sed tristique nunc in sapien luctus, ac
                euismod turpis laoreet. Fusce sit amet eros nec ante dignissim
                condimentum. Fusce vitae laoreet sapien.
            </p>
        </section>
    </div>
</body>
</html>

app/templates/registrar.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario de Registro</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: red;
            text-align: center;
            background-image: url('{{ url_for('static', filename='/imagenes/social-media.jpg') }}');
            background-size: cover;
            background-position: center;
        }

        form {
            max-width: 400px;
            margin: 0 auto;
            margin-top: 39px;
            text-align: left;
            border: 2px solid red;
            padding: 20px;
            border-radius: 10px;
            background-color: black;
            color: white;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="email"],
        input[type="password"] {
            padding: 10px;
            width: 200px;
            margin-bottom: 10px;
            border: none;
            border-radius: 5px;
        }

        input[type="submit"] {
            padding: 10px 20px;
            background-color: red;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            color: red;
            font-size: 14px;
            margin-top: 10px;
        }

        .boton {
            display: flex;
            flex-direction: column;
        }

        .centrar {
            display: flex;
            align-items: center;
            justify-content: center; /* Para centrar horizontalmente */
            height: 100vh; /* Ajusta la altura para que ocupe toda la pantalla */
        }

        h2 {
            color: white;
        }
    </style>
</head>

<body>
    <div class="centrar">
        <form action="{{ url_for('Celador.add') }}" method="post">
            <h2>CREA TU USUARIO</h2>
            <label for="cedula">Cedula:</label>
            <input type="text" id="cedula" name="cedula" required>

            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" required>

            <label for="apellido">Apellido:</label>
            <input type="text" id="apellido" name="apellido" required>

            <label for="telefono">Teléfono:</label>
            <input type="text" id="telefono" name="telefono" required>

            <label for="password">Contraseña:</label>
            <div class="boton">
                <input type="password" id="password" name="contraseña" required>

                <input type="submit" value="Registrar">
            </div>
        </form>
    </div>
</body>

</html>